[package]
name = "typst-ts-web-compiler"
description = "Compile Typst documents in Web environment."
authors.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true


[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]

ansi-to-html.workspace = true

comemo.workspace = true
base64.workspace = true

serde.workspace = true
serde-wasm-bindgen.workspace = true
serde_json.workspace = true

# Everything to do with wasm
wasm-bindgen.workspace = true
js-sys.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = [
    "console",
    "Performance",
    "PerformanceTiming",
    "Window",
    "Blob",
    "Document",
] }
console_error_panic_hook.workspace = true

reflexo-typst2vec.workspace = true
reflexo-typst = { workspace = true, features = ["web"] }
reflexo-vec2svg.workspace = true
typst.workspace = true
typst-assets = { workspace = true, optional = true }
typst-ide.workspace = true
tinymist-world.workspace = true

[dev-dependencies]
wasm-bindgen-test.workspace = true
typst-ts-test-common.workspace = true
hex.workspace = true
sha2.workspace = true
web-sys = { workspace = true, features = ["console"] }
tiny-skia-path.workspace = true

[features]
full = ["web", "web_test", "fonts", "misc"]
misc = ["incr", "svg", "pdf", "ast", "semantic_tokens", "incr-glyph-maps"]

web = ["reflexo-typst/web"]
web_test = ["typst-ts-test-common/web_artifacts"]

fonts = ["reflexo-typst/fonts", "typst-assets/fonts"]
incr = []
pdf = ["reflexo-typst/pdf"]
svg = ["reflexo-typst/svg"]
ast = ["reflexo-typst/ast"]
semantic_tokens = []

# Collect and fuse glyphMaps during typst2vec traversal.
incr-glyph-maps = ["reflexo-typst2vec/incr-glyph-maps"]

no-content-hint = [
    "reflexo-typst2vec/no-content-hint",
    "reflexo-typst/no-content-hint",
    "reflexo-vec2svg/no-content-hint",
]

[lints]
workspace = true

# https://github.com/trunk-rs/trunk/issues/991
[package.metadata.wasm-pack.profile.profiling]
wasm-opt = [
    '-O',
    '--enable-bulk-memory',
    '--enable-sign-ext',
    '--enable-nontrapping-float-to-int',
]

[package.metadata.wasm-pack.profile.release]
wasm-opt = [
    '-O',
    '--enable-bulk-memory',
    '--enable-sign-ext',
    '--enable-nontrapping-float-to-int',
]
